language: java
jdk: oraclejdk9

before_install:
 - chmod +x gradlew

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
 - ./gradlew clean install
 - ./gradlew check jTR jqa
